// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/teamService.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/teamService.go -destination=internal/mocks/mockTeamService.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/jacobpq/soccer-manager/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockTeamService is a mock of TeamService interface.
type MockTeamService struct {
	ctrl     *gomock.Controller
	recorder *MockTeamServiceMockRecorder
	isgomock struct{}
}

// MockTeamServiceMockRecorder is the mock recorder for MockTeamService.
type MockTeamServiceMockRecorder struct {
	mock *MockTeamService
}

// NewMockTeamService creates a new mock instance.
func NewMockTeamService(ctrl *gomock.Controller) *MockTeamService {
	mock := &MockTeamService{ctrl: ctrl}
	mock.recorder = &MockTeamServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamService) EXPECT() *MockTeamServiceMockRecorder {
	return m.recorder
}

// GetMyTeam mocks base method.
func (m *MockTeamService) GetMyTeam(ctx context.Context, userID int) (*service.TeamResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyTeam", ctx, userID)
	ret0, _ := ret[0].(*service.TeamResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyTeam indicates an expected call of GetMyTeam.
func (mr *MockTeamServiceMockRecorder) GetMyTeam(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyTeam", reflect.TypeOf((*MockTeamService)(nil).GetMyTeam), ctx, userID)
}

// UpdatePlayer mocks base method.
func (m *MockTeamService) UpdatePlayer(ctx context.Context, userID, playerID int, first, last, country *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlayer", ctx, userID, playerID, first, last, country)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePlayer indicates an expected call of UpdatePlayer.
func (mr *MockTeamServiceMockRecorder) UpdatePlayer(ctx, userID, playerID, first, last, country any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlayer", reflect.TypeOf((*MockTeamService)(nil).UpdatePlayer), ctx, userID, playerID, first, last, country)
}

// UpdateTeam mocks base method.
func (m *MockTeamService) UpdateTeam(ctx context.Context, userID int, name, country *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTeam", ctx, userID, name, country)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTeam indicates an expected call of UpdateTeam.
func (mr *MockTeamServiceMockRecorder) UpdateTeam(ctx, userID, name, country any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTeam", reflect.TypeOf((*MockTeamService)(nil).UpdateTeam), ctx, userID, name, country)
}
