// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/transfetService.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/transfetService.go -destination=internal/mocks/mockTransferService.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/jacobpq/soccer-manager/internal/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockTransferService is a mock of TransferService interface.
type MockTransferService struct {
	ctrl     *gomock.Controller
	recorder *MockTransferServiceMockRecorder
	isgomock struct{}
}

// MockTransferServiceMockRecorder is the mock recorder for MockTransferService.
type MockTransferServiceMockRecorder struct {
	mock *MockTransferService
}

// NewMockTransferService creates a new mock instance.
func NewMockTransferService(ctrl *gomock.Controller) *MockTransferService {
	mock := &MockTransferService{ctrl: ctrl}
	mock.recorder = &MockTransferServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransferService) EXPECT() *MockTransferServiceMockRecorder {
	return m.recorder
}

// BuyPlayer mocks base method.
func (m *MockTransferService) BuyPlayer(ctx context.Context, userID, playerID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuyPlayer", ctx, userID, playerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// BuyPlayer indicates an expected call of BuyPlayer.
func (mr *MockTransferServiceMockRecorder) BuyPlayer(ctx, userID, playerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuyPlayer", reflect.TypeOf((*MockTransferService)(nil).BuyPlayer), ctx, userID, playerID)
}

// GetMarket mocks base method.
func (m *MockTransferService) GetMarket(ctx context.Context) ([]*models.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMarket", ctx)
	ret0, _ := ret[0].([]*models.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMarket indicates an expected call of GetMarket.
func (mr *MockTransferServiceMockRecorder) GetMarket(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMarket", reflect.TypeOf((*MockTransferService)(nil).GetMarket), ctx)
}

// ListPlayer mocks base method.
func (m *MockTransferService) ListPlayer(ctx context.Context, userID, playerID int, price float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPlayer", ctx, userID, playerID, price)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListPlayer indicates an expected call of ListPlayer.
func (mr *MockTransferServiceMockRecorder) ListPlayer(ctx, userID, playerID, price any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPlayer", reflect.TypeOf((*MockTransferService)(nil).ListPlayer), ctx, userID, playerID, price)
}

// RemoveFromList mocks base method.
func (m *MockTransferService) RemoveFromList(ctx context.Context, userID, playerID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromList", ctx, userID, playerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromList indicates an expected call of RemoveFromList.
func (mr *MockTransferServiceMockRecorder) RemoveFromList(ctx, userID, playerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromList", reflect.TypeOf((*MockTransferService)(nil).RemoveFromList), ctx, userID, playerID)
}
